In [1]:
import numpy as np

In [2]:
arr = np.array([2,4,6,8])

In [3]:
print("Mảng: ", arr)

Mảng:  [2 4 6 8]


In [4]:
print("Phần tử ở vị trí số 2: ", arr[2])

Phần tử ở vị trí số 2:  6


In [5]:
matrix = np.array([[1, 3, 5], [2, 4, 6], [7, 8, 9]])
print("Mảng 2 chiều:")
print(matrix)

e = matrix[2, 1]
print("Phần tử ở hàng 2 cột 1: ", e)

Mảng 2 chiều:
[[1 3 5]
 [2 4 6]
 [7 8 9]]
Phần tử ở hàng 2 cột 1:  8


In [6]:
arr = np.zeros(10)
print("Mảng có 10 số 0: ", arr)

arr = np.ones(3)
print("Mảng có 3 số 1: ", arr)

arr = np.empty(5)
print("Mảng rỗng: ", arr)

arr = np.arange(30)
print("Mảng tăng dần từ 0 đến 29", arr)

arr = np.linspace(3, 12, num=4)
print("Mảng gồm 4 số có khoảng cách bằng nhau: ", arr)

arr = np.ones(3, dtype=np.int64)
arr

Mảng có 10 số 0:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Mảng có 3 số 1:  [1. 1. 1.]
Mảng rỗng:  [6.23042070e-307 4.67296746e-307 1.69121096e-306 1.33511562e-306
 3.59412945e-317]
Mảng tăng dần từ 0 đến 29 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Mảng gồm 4 số có khoảng cách bằng nhau:  [ 3.  6.  9. 12.]


array([1, 1, 1], dtype=int64)

In [7]:
arr = np.array([1, 5, 3, 7, 9])
print("Mảng: ", arr)

Mảng:  [1 5 3 7 9]


In [10]:
arr = np.sort(arr)
print("Sắp xếp tăng dần: ", arr)

Sắp xếp tăng dần:  [1 3 5 7 9]


In [11]:
arr = np.sort(arr)[::-1]
print("Sắp xếp ngược: ", arr)

Sắp xếp ngược:  [9 7 5 3 1]


In [12]:
arr = np.append(arr, 11)
print("Thêm phần tử vào cuối mảng: ", arr)

Thêm phần tử vào cuối mảng:  [ 9  7  5  3  1 11]


In [13]:
arr = np.delete(arr, 4)
print("Xóa phần tử ở vị trí số 4: ", arr)

Xóa phần tử ở vị trí số 4:  [ 9  7  5  3 11]


In [16]:
arr = np.array([[9, 7, 8],
                [3, 1, 2],
                [5, 6, 4]])

sorted_by_row = np.sort(arr, axis=1)
print("Sắp xếp hàng tăng dần: ")
print(sorted_by_row)

sorted_by_column = np.sort(arr, axis=0)
print("Sắp xếp cột tăng dần: ")
print(sorted_by_column)

sorted_by_row = -np.sort(-arr, axis=1)
print("Sắp xếp hàng giảm dần: ")
print(sorted_by_row)

sorted_by_row = -np.sort(-arr, axis=0)
print("Sắp xếp cột giảm dần: ")
print(sorted_by_row)

Sắp xếp hàng tăng dần: 
[[7 8 9]
 [1 2 3]
 [4 5 6]]
Sắp xếp cột tăng dần: 
[[3 1 2]
 [5 6 4]
 [9 7 8]]
Sắp xếp hàng giảm dần: 
[[9 8 7]
 [3 2 1]
 [6 5 4]]
Sắp xếp cột giảm dần: 
[[9 7 8]
 [5 6 4]
 [3 1 2]]


In [18]:
arr = np.array([[1, 3, 5], [2, 4, 6]])
ndim = arr.ndim
size = arr.size
shape = arr.shape

print("Số chiều: ", ndim)
print("Kích thước: ", size)
print("Số hàng - số cột: ", shape)

Số chiều:  2
Kích thước:  6
Số hàng - số cột:  (2, 3)


In [19]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(float)
print("Đổi kiểu dữ liệu mảng: ", float_arr)

Đổi kiểu dữ liệu mảng:  [1. 2. 3. 4. 5.]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print("Đổi thành mảng 2 chiều có 2 hàng 3 cột:")
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print("Đổi thành mảng 2 chiều có 3 hàng 2 cột:")
print(reshaped_arr)

Đổi thành mảng 2 chiều có 2 hàng 3 cột:
[[1 2 3]
 [4 5 6]]
Đổi thành mảng 2 chiều có 3 hàng 2 cột:
[[1 2]
 [3 4]
 [5 6]]


In [23]:
reshaped_arr = reshaped_arr.flatten()
print("Đổi mảng 2 chiều thành 1 chiều: ", reshaped_arr)

Đổi mảng 2 chiều thành 1 chiều:  [1 2 3 4 5 6]


In [25]:
arr = np.array([1, 3, 5, 7, 9])

array_slice = arr[1:4]
print("Cắt phần tử 1 đến phần tử 3: ", array_slice)

Cắt phần tử 1 đến phần tử 3:  [3 5 7]


In [26]:
array_slice = arr[:-1]
print("Cắt phần tử 1 đến phần tử cuối - 1:", array_slice)

Cắt phần tử 1 đến phần tử cuối - 1: [1 3 5 7]


In [27]:
array_slice = arr[-3:]
print("Cắt phần tử 3 tính từ cuối mảng đến hết:", array_slice)

Cắt phần tử 3 tính từ cuối mảng đến hết: [5 7 9]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T
print("Hoán đổi hàng thành cột:")
print(transposed_arr)

Hoán đổi hàng thành cột:
[[1 4]
 [2 5]
 [3 6]]


In [31]:
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 3, 5])
new_arr = np.concatenate((arr1, arr2))
print("Nối mảng: ", new_arr)

Nối mảng:  [2 4 6 1 3 5]


In [32]:
arr = np.array([1, 2, 3, 4, 5])
sum_array = np.sum(arr)
print("Tổng của mảng:", sum_array)

Tổng của mảng: 15


In [33]:
average = np.mean(arr)
print("Giá trị trung bình của mảng:", average)

Giá trị trung bình của mảng: 3.0


In [34]:
max = np.max(arr)
min = np.min(arr)
print("Giá trị lớn nhất:", max)
print("Giá trị nhỏ nhất:", min)

Giá trị lớn nhất: 5
Giá trị nhỏ nhất: 1


In [36]:
std = np.std(arr)
print("Độ lệch chuẩn của mảng:", std)

Độ lệch chuẩn của mảng: 1.4142135623730951


In [37]:
variance = np.var(arr)
print("Phương sai của mảng:", variance)

Phương sai của mảng: 2.0


In [38]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của hai mảng:", dot_product)

Tổng tích chập của hai mảng: 32
